### PR TITLE
Add data and likelihoods for Lya BAO analyses from BOSS/eBOSS

### PR DESCRIPTION
**Pull request by jfarr03**
This PR adds code to read the chi-squared scans in BAO parameter space from recent Lya-forest surveys, and use these values in a likelihood. This enables users to avoid using the normal Gaussian approximation, and more accurately quantify the cosmological constraints that Lya-forest surveys are able to impose.

### CODE REVIEW

**Comment by andreufont** [comment]
Hi @brinckmann , @lesgourg - Is there anything we could do to help with this PR? Thanks.

**Comment by brinckmann** [comment]
Hi Andreu,

I apologize for the long delay! I'm putting out a new v3.2 with Planck 2018 today and I am including your likelihoods as a part of it. I have been in touch with James and I think everything is clear on what to do. Thanks!

Best,
Thejs

**Comment by andreufont** [comment]
Great. Thanks!

**Comment by brinckmann** [comment]
It's done! Thanks @jfarr03 and @andreufont !

**Pull request merged**
